# <-------------stage1------------->
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# <-------------stage2------------->
FROM node:18-alpine

RUN npm install -g serve

# create non-root user
RUN adduser -D appuser

# Copy build output
COPY --from=builder /app/build ./build

USER appuser

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]

